routes/web.php
<?php

//AdminRoutes

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {

        Route::get('/home', 'HomeController@index')->name('admin.home');
        Route::resource('/admins', 'AdminController');
        Route::resource('/products', 'ProductController');
        Route::post('/products/change', 'ProductController@change');
        Route::resource('/users', 'UserController');
        Route::resource('/coupons', 'CouponController');
        Route::post('/coupon/send', 'CouponController@sendCoupon')->name('coupons.send');
        Route::post('/users/sendMail', 'UserController@sendMail')->name('users.sendMail');
        Route::get('/orders', 'OrderController@index')->name('orders.index');
        Route::post('/yes_order', 'OrderController@YesFunction')->name('order.yes');
        Route::post('/accept_order', 'OrderController@AcceptFunction')->name('order.accept');
        Route::post('/no_order', 'OrderController@NoFunction')->name('order.no');
        Route::get('/fulfilled_order', 'FulfilledOrderController@index')->name('fulfilled_order.index');
        Route::get('/analytics', 'AnalyticController@index')->name('analytics.index');
        Route::post('/analytics/sales', 'AnalyticController@sales')->name('analytics.sales');

        // AdminAuth
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');

        // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    });
});

//UserRoutes

Route::namespace('User')->group(function () {
    Route::get('/home','HomeController@index')->name('home');
    Route::get('/profile','ProfileController@index')->name('profile');
    Route::post('/profile','ProfileController@info')->name('profile.info');
    Route::get('cart','CartController@index')->name('cart');
    Route::post('cart','CartController@store')->name('cart.store');
    Route::post('/cart/delete','CartController@delete')->name('cart.delete');
    Route::post('/cart/qty','CartController@qty')->name('cart.qty');
    Route::post('/coupon','CouponController@coupon')->name('coupon');
    Route::get('/coupon/destroy','CouponController@destroy')->name('coupon.destroy');
    Route::post('/contact','HomeController@contact')->name('contact');
    Route::get('/pre-checkout','CheckoutController@index')->name('pre-checkout');
    Route::post('/checkout','CheckoutController@store')->name('pre-checkout.store');
    Route::post('/order','OrderController@store')->name('order.delivery');
    Route::get('/', function () { return view('user.preload'); });

    Route::post('/payment_paypal','PaymentController@payment_paypal')->name('payment_paypal');
    Route::get('/status', 'PaymentController@getPaymentStatus')->name('status');

    Route::post('/payment_credit_card','PaymentController@payment_credit_card')->name('payment_credit_card');

    Route::get('404', function () {
        return view('user.404');
    })->name('404');

    Route::get('checkout', function () {
        return view('user.checkout');
    });


    //UserAuth
    Auth::routes();

    Route::get('/login/google', 'Auth\LoginController@redirectToProvider')->name('google.login');
    Route::get('/login/google/callback', 'Auth\LoginController@handleProviderCallback');
});

resources/views/admin/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    @include('admin.layouts.head')
    @section('head-part')
    @show
</head>
<body class="hold-transition skin-red sidebar-mini">
<div class="wrapper">
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')

        @section('body-part')
            @show

    @include('admin.layouts.footer')
</div>
@include('admin.layouts.script')
@section('script-part')
    @show
</body>
</html>

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
</footer>

resources/views/admin/layouts/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Donair Spice | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/Ionicons/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admin/dist/css/AdminLTE.min.css') }}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <!-- Morris charts -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/morris.js/morris.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/jvectormap/jquery-jvectormap.css') }}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('admin/dist/css/skins/_all-skins.min.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="{{ asset('user/assets/css/product.css') }}">

    <link rel="icon" href="{{ asset('/images/logo-ico.jpg') }}">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <style>
        /**
        * Checkbox Four
        */
        .checkboxFour {
            width: 40px;
            height: 40px;
            background: #ddd;
            margin: 10px 10px;

            border-radius: 100%;
            position: relative;
            box-shadow: 0px 1px 3px rgba(0,0,0,0.5);
        }
        /**
         * Create the checkbox button
         */
        .checkboxFour label {
            display: block;
            width: 30px;
            height: 30px;
            border-radius: 100px;

            transition: all .5s ease;
            cursor: pointer;
            position: absolute;
            top: 5px;
            left: 5px;
            z-index: 1;

            background: #333;
            box-shadow:inset 0px 1px 3px rgba(0,0,0,0.5);
        }
        /**
         * Create the checked state
         */
        .checkboxFour input[type=checkbox]:checked + label {
            background: rgb(215,57,37);
        }
    </style>
</head>

resources/views/admin/layouts/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('admin.home') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>D</b>S</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Donair</b>SPICE</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ asset('images/profile.jpg') }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ asset('images/profile.jpg') }}" class="img-circle" alt="User Image">

                            <p>
                                {{ Auth::user()->name }} - Administrator
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">

                            <div class="pull-right">
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">Sign out</a>
                            </div>

                            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/script.blade.php
<!-- jQuery 3 -->
<script src="{{ asset('admin/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('admin/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('admin/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<!-- jvectormap -->
<script src="{{ asset('admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>

<!-- Morris.js charts -->
<script src="{{ asset('admin/bower_components/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/morris.js/morris.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('admin/bower_components/chart.js/Chart.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>

<!-- daterangepicker -->
<script src="{{ asset('admin/bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('admin/dist/js/pages/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin/dist/js/demo.js') }}"></script>
<script>
    $(document).ready(function () {
        $('.sidebar-menu').tree()
    })
</script>

<!-- page script -->
<script>
    $(function () {
        $('#example1').DataTable()
        $('#example2').DataTable({
            'paging'      : true,
            'lengthChange': false,
            'searching'   : false,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : false
        })
    })
</script>

resources/views/admin/layouts/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('images/profile.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="@yield('Dashboard')"><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
            <li class="@yield('Order') @yield('Fulfilled Orders') treeview">
                <a href="#">
                    <i class="fa fa-shopping-cart"></i> <span>Orders</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@yield('Order')"><a href="{{ route('orders.index') }}"><i class="fa fa-circle-o"></i> Orders</a></li>
                    <li class="@yield('Fulfilled Orders')"><a href="{{ route('fulfilled_order.index') }}"><i class="fa fa-circle-o"></i> Fulfilled Orders</a></li>
                </ul>
            </li>

            <li class="@yield('Analytics')"><a href="{{ route('analytics.index') }}"><i class="fa fa-signal"></i> <span>Analytics</span></a></li>
            <li class="@yield('Products')"><a href="{{ route('products.index') }}"><i class="fa fa-folder-o"></i> <span>Products</span></a></li>
            <li class="@yield('Admins')"><a href="{{ route('admins.index') }}"><i class="fa fa-user"></i> <span>Admins</span></a></li>
            <li class="@yield('Customers')"><a href="{{ route('users.index') }}"><i class="fa fa-users"></i> <span>Customers</span></a></li>
            <li class="@yield('Coupons')"><a href="{{ route('coupons.index') }}"><i class="fa fa-ticket"></i> <span>Coupons</span></a></li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>