routes/web.php
<?php

//AdminRoutes

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {

        Route::get('/home', 'HomeController@index')->name('admin.home');
        Route::resource('/admins', 'AdminController');
        Route::resource('/products', 'ProductController');
        Route::post('/products/change', 'ProductController@change');
        Route::resource('/users', 'UserController');
        Route::resource('/coupons', 'CouponController');
        Route::post('/coupon/send', 'CouponController@sendCoupon')->name('coupons.send');
        Route::post('/users/sendMail', 'UserController@sendMail')->name('users.sendMail');
        Route::get('/orders', 'OrderController@index')->name('orders.index');
        Route::post('/yes_order', 'OrderController@YesFunction')->name('order.yes');
        Route::post('/accept_order', 'OrderController@AcceptFunction')->name('order.accept');
        Route::post('/no_order', 'OrderController@NoFunction')->name('order.no');
        Route::get('/fulfilled_order', 'FulfilledOrderController@index')->name('fulfilled_order.index');
        Route::get('/analytics', 'AnalyticController@index')->name('analytics.index');
        Route::post('/analytics/sales', 'AnalyticController@sales')->name('analytics.sales');

        // AdminAuth
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');

        // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    });
});

//UserRoutes

Route::namespace('User')->group(function () {
    Route::get('/home','HomeController@index')->name('home');
    Route::get('/profile','ProfileController@index')->name('profile');
    Route::post('/profile','ProfileController@info')->name('profile.info');
    Route::get('cart','CartController@index')->name('cart');
    Route::post('cart','CartController@store')->name('cart.store');
    Route::post('/cart/delete','CartController@delete')->name('cart.delete');
    Route::post('/cart/qty','CartController@qty')->name('cart.qty');
    Route::post('/coupon','CouponController@coupon')->name('coupon');
    Route::get('/coupon/destroy','CouponController@destroy')->name('coupon.destroy');
    Route::post('/contact','HomeController@contact')->name('contact');
    Route::get('/pre-checkout','CheckoutController@index')->name('pre-checkout');
    Route::post('/checkout','CheckoutController@store')->name('pre-checkout.store');
    Route::post('/order','OrderController@store')->name('order.delivery');
    Route::get('/', function () { return view('user.preload'); });

    Route::post('/payment_paypal','PaymentController@payment_paypal')->name('payment_paypal');
    Route::get('/status', 'PaymentController@getPaymentStatus')->name('status');

    Route::post('/payment_credit_card','PaymentController@payment_credit_card')->name('payment_credit_card');

    Route::get('404', function () {
        return view('user.404');
    })->name('404');

    Route::get('checkout', function () {
        return view('user.checkout');
    });


    //UserAuth
    Auth::routes();

    Route::get('/login/google', 'Auth\LoginController@redirectToProvider')->name('google.login');
    Route::get('/login/google/callback', 'Auth\LoginController@handleProviderCallback');
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('admin.products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'description' => 'required',
            'price' => 'required',
            'size' => 'required',
            'image-data' => 'required',
        ]);

        $imageData = $request->get('image-data');
        $info = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $imageData));
        $imageName = 'public/'.str_random(16).'.jpg';
        Storage::put($imageName,$info);

        $product = new Product();

        $product->name = $request->name;
        $product->image = $imageName;
        $product->description = $request->description;
        $product->price = $request->price;
        $product->size = $request->size;
        $product->nutrition_label = $request->nutrition_label;
        $product->inventory_status = $request->inventory_status;

        $product->save();

        return redirect()->route('products.index')->with('message_alert','Successfully created product!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::where('id',$id)->first();

        return view('admin.products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'description' => 'required',
            'price' => 'required',
            'size' => 'required'
        ]);

        $product = Product::where('id',$id)->first();

        $product->name = $request->name;
        $product->description = $request->description;
        $product->price = $request->price;
        $product->size = $request->size;
        $product->nutrition_label = $request->nutrition_label;

        if ($request->get('image-data')) {

            Storage::delete($product->image);

            $imageData = $request->get('image-data');
            $info = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $imageData));
            $imageName = 'public/'.str_random(16).'.jpg';
            Storage::put($imageName,$info);

            $product->image = $imageName;
        }

        $product->save();

        return redirect()->route('products.index')->with('message_alert','Successfully updated product!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::where('id',$id)->first();
        Storage::delete($product->image);
        $product->delete();

        return redirect()->route('products.index')->with('message_alert','Successfully deleted product!');
    }

    public function change(Request $request)
    {
        $product = Product::where('id',$request->id)->first();

        $product->inventory_status = $request->status;

        $product->save();
    }
}

resources/views/admin/products/create.blade.php
@section('Products','active')
<!doctype html>
<html lang="en">
<head>
    @include('admin.layouts.head')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{{ asset('/js/cropit.js') }}"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <style>
        .cropit-preview {
            background-color: #f8f8f8;
            background-size: cover;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-top: 7px;
            width: 400px;
            height: 300px;
        }

        .cropit-preview-image-container {
            cursor: move;
        }

        .image-size-label {
            margin-top: 10px;
        }

        input {
            display: block;
        }

        button[type="submit"] {
            margin-top: 10px;
        }

        #result {
            margin-top: 10px;
            width: 900px;
        }

        #result-data {
            display: block;
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
            word-wrap: break-word;
        }

        .slidecontainer {
            width: 100%;
        }

        .slider {
            -webkit-appearance: none;
            width: 100%;
            height: 25px;
            background: #d3d3d3;
            outline: none;
            opacity: 0.7;
            -webkit-transition: .2s;
            transition: opacity .2s;
        }

        .slider:hover {
            opacity: 1;
        }

        .slider::-webkit-slider-thumb {
            -webkit-appearance: none;
            appearance: none;
            width: 25px;
            height: 25px;
            background: rgb(215,57,37);
            cursor: pointer;
        }

        .slider::-moz-range-thumb {
            width: 25px;
            height: 25px;
            background: rgb(215,57,37);
            cursor: pointer;
        }
    </style>
</head>
<body class="hold-transition skin-red sidebar-mini">
<div class="wrapper">
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')

    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Create Product</h3>
                            <br>
                            @include('errors.error')
                            <a href="{{ route('products.index') }}"><button class="btn btn-flat btn-success">Back</button></a>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Product Name</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Enter Name" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Description</label>
                                    <input type="text" name="description" class="form-control" id="exampleInputEmail1" placeholder="Enter Description" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Price</label>
                                    <input type="number" name="price" step="any" class="form-control" id="exampleInputEmail1" placeholder="Enter Price" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Size</label>
                                    <input type="text" name="size" class="form-control" id="exampleInputEmail1" placeholder="Enter Size" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Nutrition Label</label>
                                    <input type="text" name="nutrition_label" class="form-control" id="exampleInputEmail1" placeholder="Enter Nutrition Label" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Inventory status</label>
                                    <input type="number" name="inventory_status" class="form-control" id="exampleInputEmail1" placeholder="Enter Inventory Status" required>
                                </div>

                                <div class="form-group image-editor slidecontainer">
                                    <label for="exampleInputEmail1">Product Image</label>
                                    <input type="file" class="cropit-image-input" required>
                                    <div class="cropit-preview"></div>
                                    <br>
                                    <div class="col-lg-5">
                                        <input type="range" class="cropit-image-zoom-input slider" id="myRange">
                                    </div>
                                    <div class="col-lg-8">
                                        <input type="hidden" name="image-data" class="hidden-image-data" />
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

    @include('admin.layouts.footer')
</div>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>

<!-- Morris.js charts -->
<script src="{{ asset('admin/bower_components/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/morris.js/morris.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('admin/bower_components/chart.js/Chart.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<!-- AdminLTE App -->
<script src="{{ asset('admin/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin/dist/js/demo.js') }}"></script>
<script>
    $(document).ready(function () {
        $('.sidebar-menu').tree()
    })
</script>

<!-- page script -->
<script>
    $(function () {
        $('#example1').DataTable()
        $('#example2').DataTable({
            'paging'      : true,
            'lengthChange': false,
            'searching'   : false,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : false
        })
    })
</script>

<script>
    $(function() {
        $('.image-editor').cropit({'minZoom':2});

        $('form').submit(function() {
            // Move cropped image data to hidden input
            var imageData = $('.image-editor').cropit('export');
            $('.hidden-image-data').val(imageData);

            // Print HTTP request params
            var formValue = $(this).serialize();
            $('#result-data').text(formValue);

            // Prevent the form from actually submitting
            return true;
        });
    });
</script>
</body>
</html>

resources/views/admin/products/edit.blade.php
@section('Products','active')
<!doctype html>
<html lang="en">
<head>
    @include('admin.layouts.head')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{{ asset('/js/cropit.js') }}"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <style>
        .cropit-preview {
            background-color: #f8f8f8;
            background-size: cover;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-top: 7px;
            width: 400px;
            height: 300px;
        }

        .cropit-preview-image-container {
            cursor: move;
        }

        .image-size-label {
            margin-top: 10px;
        }

        input {
            display: block;
        }

        button[type="submit"] {
            margin-top: 10px;
        }

        #result {
            margin-top: 10px;
            width: 900px;
        }

        #result-data {
            display: block;
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
            word-wrap: break-word;
        }

        .slidecontainer {
            width: 100%;
        }

        .slider {
            -webkit-appearance: none;
            width: 100%;
            height: 25px;
            background: #d3d3d3;
            outline: none;
            opacity: 0.7;
            -webkit-transition: .2s;
            transition: opacity .2s;
        }

        .slider:hover {
            opacity: 1;
        }

        .slider::-webkit-slider-thumb {
            -webkit-appearance: none;
            appearance: none;
            width: 25px;
            height: 25px;
            background: rgb(215,57,37);
            cursor: pointer;
        }

        .slider::-moz-range-thumb {
            width: 25px;
            height: 25px;
            background: rgb(215,57,37);
            cursor: pointer;
        }
    </style>
</head>
<body class="hold-transition skin-red sidebar-mini">
<div class="wrapper">
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')

    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit Product</h3>
                            <br>
                            @include('errors.error')
                            <a href="{{ route('products.index') }}"><button class="btn btn-flat btn-success">Back</button></a>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Product Name</label>
                                    <input type="text" name="name" class="form-control" value="{{ $product->name }}" id="exampleInputEmail1" placeholder="Enter Name" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Description</label>
                                    <input type="text" name="description" class="form-control" value="{{ $product->description }}" id="exampleInputEmail1" placeholder="Enter Description" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Price</label>
                                    <input type="number" name="price" step="any" class="form-control" value="{{ $product->price }}" id="exampleInputEmail1" placeholder="Enter Price" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Size</label>
                                    <input type="text" name="size" class="form-control" value="{{ $product->size }}" id="exampleInputEmail1" placeholder="Enter Size" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Nutrition Label</label>
                                    <input type="text" name="nutrition_label" class="form-control" value="{{ $product->nutrition_label }}" id="exampleInputEmail1" placeholder="Enter Nutrition Label" required>
                                </div>

                                <div class="form-group image-editor slidecontainer">
                                    <label for="exampleInputEmail1">Product Image</label>
                                    <input type="file" class="cropit-image-input">
                                    <div class="cropit-preview"></div>
                                    <br>
                                    <div class="col-lg-5">
                                        <input type="range" class="cropit-image-zoom-input slider" id="myRange">
                                    </div>
                                    <div class="col-lg-8">
                                        <input type="hidden" name="image-data" class="hidden-image-data" />
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

    @include('admin.layouts.footer')
</div>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>

<!-- Morris.js charts -->
<script src="{{ asset('admin/bower_components/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/morris.js/morris.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('admin/bower_components/chart.js/Chart.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<!-- AdminLTE App -->
<script src="{{ asset('admin/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin/dist/js/demo.js') }}"></script>
<script>
    $(document).ready(function () {
        $('.sidebar-menu').tree()
    })
</script>

<!-- page script -->
<script>
    $(function () {
        $('#example1').DataTable()
        $('#example2').DataTable({
            'paging'      : true,
            'lengthChange': false,
            'searching'   : false,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : false
        })
    })
</script>

<script>
    $(function() {
        $('.image-editor').cropit({'minZoom':2});

        $('form').submit(function() {
            // Move cropped image data to hidden input
            var imageData = $('.image-editor').cropit('export');
            $('.hidden-image-data').val(imageData);

            // Print HTTP request params
            var formValue = $(this).serialize();
            $('#result-data').text(formValue);

            // Prevent the form from actually submitting
            return true;
        });
    });
</script>
</body>
</html>