routes/web.php
<?php

//AdminRoutes

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {

        Route::get('/home', 'HomeController@index')->name('admin.home');
        Route::resource('/admins', 'AdminController');
        Route::resource('/products', 'ProductController');
        Route::post('/products/change', 'ProductController@change');
        Route::resource('/users', 'UserController');
        Route::resource('/coupons', 'CouponController');
        Route::post('/coupon/send', 'CouponController@sendCoupon')->name('coupons.send');
        Route::post('/users/sendMail', 'UserController@sendMail')->name('users.sendMail');
        Route::get('/orders', 'OrderController@index')->name('orders.index');
        Route::post('/yes_order', 'OrderController@YesFunction')->name('order.yes');
        Route::post('/accept_order', 'OrderController@AcceptFunction')->name('order.accept');
        Route::post('/no_order', 'OrderController@NoFunction')->name('order.no');
        Route::get('/fulfilled_order', 'FulfilledOrderController@index')->name('fulfilled_order.index');
        Route::get('/analytics', 'AnalyticController@index')->name('analytics.index');
        Route::post('/analytics/sales', 'AnalyticController@sales')->name('analytics.sales');

        // AdminAuth
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');

        // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    });
});

//UserRoutes

Route::namespace('User')->group(function () {
    Route::get('/home','HomeController@index')->name('home');
    Route::get('/profile','ProfileController@index')->name('profile');
    Route::post('/profile','ProfileController@info')->name('profile.info');
    Route::get('cart','CartController@index')->name('cart');
    Route::post('cart','CartController@store')->name('cart.store');
    Route::post('/cart/delete','CartController@delete')->name('cart.delete');
    Route::post('/cart/qty','CartController@qty')->name('cart.qty');
    Route::post('/coupon','CouponController@coupon')->name('coupon');
    Route::get('/coupon/destroy','CouponController@destroy')->name('coupon.destroy');
    Route::post('/contact','HomeController@contact')->name('contact');
    Route::get('/pre-checkout','CheckoutController@index')->name('pre-checkout');
    Route::post('/checkout','CheckoutController@store')->name('pre-checkout.store');
    Route::post('/order','OrderController@store')->name('order.delivery');
    Route::get('/', function () { return view('user.preload'); });

    Route::post('/payment_paypal','PaymentController@payment_paypal')->name('payment_paypal');
    Route::get('/status', 'PaymentController@getPaymentStatus')->name('status');

    Route::post('/payment_credit_card','PaymentController@payment_credit_card')->name('payment_credit_card');

    Route::get('404', function () {
        return view('user.404');
    })->name('404');

    Route::get('checkout', function () {
        return view('user.checkout');
    });


    //UserAuth
    Auth::routes();

    Route::get('/login/google', 'Auth\LoginController@redirectToProvider')->name('google.login');
    Route::get('/login/google/callback', 'Auth\LoginController@handleProviderCallback');
});

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.app')
@section('Admins','active')
@section('body-part')

    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Create Admin</h3>
                            <br>
                            @include('errors.error')
                            <a href="{{ route('admins.index') }}"><button class="btn btn-flat btn-success">Back</button></a>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('admins.store') }}" method="POST">
                            @csrf
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Admin Name</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Enter Name" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email address</label>
                                    <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter Email" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password</label>
                                    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

    @endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.app')

@section('Admins','active')
@section('body-part')

    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit Admin</h3>
                            <br>
                            @include('errors.error')
                            <a href="{{ route('admins.index') }}"><button class="btn btn-flat btn-success">Back</button></a>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('admins.update',$admin->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Admin Name</label>
                                    <input type="text" name="name" class="form-control" value="{{ $admin->name }}" id="exampleInputEmail1" placeholder="Enter Name" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email address</label>
                                    <input type="email" name="email" class="form-control" value="{{ $admin->email }}" id="exampleInputEmail1" placeholder="Enter Email" required>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.app')

@section('Admins','active')
@section('body-part')

    <div class="content-wrapper">

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">All Admins</h3>
                            <br>
                            <a href="{{ route('admins.create') }}"><button class="btn btn-flat btn-success">New</button></a>
                            @if(session()->has('message_alert'))
                                <br>
                                <br>
                                <p class="alert alert-success">{{ session('message_alert') }}</p>
                            @endif
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="table-responsive">
                                <table id="example2" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($admins as $admin)
                                        <tr>
                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>{{ $admin->name }}</td>
                                            <td>{{ $admin->email }}</td>
                                            <td>
                                                <a href="{{ route('admins.edit',$admin->id) }}">
                                                    <button class="btn btn-flat btn-block btn-warning"><span class="fa fa-edit"></span></button>
                                                </a>
                                            </td>
                                            <td>
                                                <form id="delete-form-{{ $admin->id }}" method="POST" action="{{ route('admins.destroy',$admin->id) }}" style="display: none;">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                                <a href="" onclick="if(confirm('Do you really want to delete this admin?')){
                                                        event.preventDefault();
                                                        document.getElementById('delete-form-{{ $admin->id }}').submit();
                                                        }else{
                                                        event.preventDefault();
                                                        }">
                                                    <button class="btn btn-flat btn-block btn-danger"><span class="fa fa-trash"></span></button>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

@endsection