routes/web.php
<?php

//AdminRoutes

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {

        Route::get('/home', 'HomeController@index')->name('admin.home');
        Route::resource('/admins', 'AdminController');
        Route::resource('/products', 'ProductController');
        Route::post('/products/change', 'ProductController@change');
        Route::resource('/users', 'UserController');
        Route::resource('/coupons', 'CouponController');
        Route::post('/coupon/send', 'CouponController@sendCoupon')->name('coupons.send');
        Route::post('/users/sendMail', 'UserController@sendMail')->name('users.sendMail');
        Route::get('/orders', 'OrderController@index')->name('orders.index');
        Route::post('/yes_order', 'OrderController@YesFunction')->name('order.yes');
        Route::post('/accept_order', 'OrderController@AcceptFunction')->name('order.accept');
        Route::post('/no_order', 'OrderController@NoFunction')->name('order.no');
        Route::get('/fulfilled_order', 'FulfilledOrderController@index')->name('fulfilled_order.index');
        Route::get('/analytics', 'AnalyticController@index')->name('analytics.index');
        Route::post('/analytics/sales', 'AnalyticController@sales')->name('analytics.sales');

        // AdminAuth
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');

        // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    });
});

//UserRoutes

Route::namespace('User')->group(function () {
    Route::get('/home','HomeController@index')->name('home');
    Route::get('/profile','ProfileController@index')->name('profile');
    Route::post('/profile','ProfileController@info')->name('profile.info');
    Route::get('cart','CartController@index')->name('cart');
    Route::post('cart','CartController@store')->name('cart.store');
    Route::post('/cart/delete','CartController@delete')->name('cart.delete');
    Route::post('/cart/qty','CartController@qty')->name('cart.qty');
    Route::post('/coupon','CouponController@coupon')->name('coupon');
    Route::get('/coupon/destroy','CouponController@destroy')->name('coupon.destroy');
    Route::post('/contact','HomeController@contact')->name('contact');
    Route::get('/pre-checkout','CheckoutController@index')->name('pre-checkout');
    Route::post('/checkout','CheckoutController@store')->name('pre-checkout.store');
    Route::post('/order','OrderController@store')->name('order.delivery');
    Route::get('/', function () { return view('user.preload'); });

    Route::post('/payment_paypal','PaymentController@payment_paypal')->name('payment_paypal');
    Route::get('/status', 'PaymentController@getPaymentStatus')->name('status');

    Route::post('/payment_credit_card','PaymentController@payment_credit_card')->name('payment_credit_card');

    Route::get('404', function () {
        return view('user.404');
    })->name('404');

    Route::get('checkout', function () {
        return view('user.checkout');
    });


    //UserAuth
    Auth::routes();

    Route::get('/login/google', 'Auth\LoginController@redirectToProvider')->name('google.login');
    Route::get('/login/google/callback', 'Auth\LoginController@handleProviderCallback');
});

app/Http/Controllers/Admin/CouponController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Mail\CouponSend;
use App\Model\Coupon;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

class CouponController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coupons = Coupon::all();
        return view('admin.coupons.index',compact('coupons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.coupons.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $coupon = new Coupon();

        $coupon->code = strtoupper($request->code);
        $coupon->coupon_type = $request->coupon_type;
        if ($request->coupon_type == 'fixed') {
            $coupon->price_off = $request->price_off;
        } else {
            $coupon->percent_off = $request->percent_off;
        }

        $coupon->save();

        return redirect()->route('coupons.index')->with('message_alert','Coupon successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $coupon = Coupon::where('id',$id)->first();

        return view('admin.coupons.edit',compact('coupon'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $coupon = Coupon::where('id',$id)->first();

        $coupon->code = strtoupper($request->code);
        $coupon->coupon_type = $request->coupon_type;
        if ($request->coupon_type == 'fixed') {
            $coupon->price_off = $request->price_off;
        } else {
            $coupon->percent_off = $request->percent_off;
        }

        $coupon->save();

        return redirect()->route('coupons.index')->with('message_alert','Coupon successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $coupon = Coupon::where('id',$id)->first();

        $coupon->delete();

        return redirect()->route('coupons.index')->with('message_alert','Coupon successfully deleted!');
    }
    /**
     * Send coupon to All User.
     */

    public function sendCoupon(Request $request)
    {
        $users = User::all();
        $code = $request->code;

        foreach ($users as $user) {
            $customer_email = $user->email;

            Mail::to($customer_email)->send(new CouponSend());

            $user->coupon_status = 1;

            $user->save();
        }

        return redirect()->route('coupons.index')->with('message_alert','Coupon successfully sent to all users!');
    }
}

app/Http/Controllers/User/CouponController.php
<?php

namespace App\Http\Controllers\User;

use App\Model\Coupon;
use App\User;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CouponController extends Controller
{
    public function coupon(Request $request)
    {
        $code = strtoupper($request->code);

        $user = User::where('id',$request->user_id)->first();

        if ($user->coupon_status) {

            $coupon = Coupon::where('code',$code)->first();

            if ($coupon) {

                if ($coupon->coupon_type == 'fixed') {
                    $discount = $coupon->price_off;
                    $newSubtotal = Cart::total() - $discount;
                    $discount_price = Cart::total() - $newSubtotal;

                } else {
                    $discount = $coupon->percent_off;
                    $newSubtotal = (Cart::total() / 100) * (100 - $discount);
                    $discount_price = Cart::total() - $newSubtotal;
                }

                session()->put('coupon', [
                    'name' => $code,
                    'discount' => $discount,
                    'type' => $coupon->coupon_type,
                    'discount_price' => $discount_price,
                    'newSubtotal' => $newSubtotal
                ]);

                return redirect()->back()->with('message_coupon','The coupon has been successfully used.');

            } else {
                return redirect()->back()->with('message_coupon','The coupon does not match.');
            }

        } else {
            return redirect()->back()->with('message_coupon','You already used that coupon.');
        }

    }

    public function destroy()
    {
        session()->forget('coupon');
        return redirect()->back()->with('message_coupon','Coupon successfully removed.');
    }
}

resources/views/admin/coupons/create.blade.php
@extends('admin.layouts.app')
@section('Coupons','active')
@section('body-part')

    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Create Coupon</h3>
                            <br>
                            @include('errors.error')
                            <a href="{{ route('coupons.index') }}"><button class="btn btn-flat btn-success">Back</button></a>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('coupons.store') }}" method="POST">
                            @csrf
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Code</label>
                                    <input type="text" name="code" class="form-control" id="exampleInputEmail1" placeholder="Enter Code" style="text-transform: uppercase;" required>
                                </div>
                                <div>
                                    <label for="exampleInputEmail1">Coupon Type</label>
                                    <select name="coupon_type" class="form-control">
                                        <option value="percent">Percent</option>
                                        <option value="fixed">Fixed</option>
                                    </select>
                                    <br>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Percent Off(%)</label>
                                    <input type="number" step="any" name="percent_off" class="form-control" id="exampleInputEmail1" placeholder="Enter percent">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Price Off($)</label>
                                    <input type="number" step="any" name="price_off" class="form-control" id="exampleInputEmail1" placeholder="Enter price">
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

    @endsection

resources/views/admin/coupons/edit.blade.php
@extends('admin.layouts.app')
@section('Coupons','active')
@section('body-part')

    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit Coupon</h3>
                            <br>
                            @include('errors.error')
                            <a href="{{ route('coupons.index') }}"><button class="btn btn-flat btn-success">Back</button></a>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('coupons.update',$coupon->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Code</label>
                                    <input type="text" name="code" class="form-control" value="{{ $coupon->code }}" id="exampleInputEmail1" placeholder="Enter Code" style="text-transform: uppercase;" required>
                                </div>
                                <div>
                                    <label for="exampleInputEmail1">Coupon Type</label>
                                    <select name="coupon_type" class="form-control">
                                        <option value="percent" @if($coupon->coupon_type == 'percent') selected @endif>Percent</option>
                                        <option value="fixed" @if($coupon->coupon_type == 'fixed') selected @endif>Fixed</option>
                                    </select>
                                    <br>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Percent Off(%)</label>
                                    <input type="number" step="any" name="percent_off" value="{{ $coupon->percent_off }}" class="form-control" id="exampleInputEmail1" placeholder="Enter percent">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Price Off($)</label>
                                    <input type="number" step="any" name="price_off" value="{{ $coupon->price_off }}" class="form-control" id="exampleInputEmail1" placeholder="Enter price">
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/admin/coupons/index.blade.php
@extends('admin.layouts.app')

@section('Coupons','active')
@section('body-part')

    <div class="content-wrapper">

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">All Coupons</h3>
                            <br>
                            <a href="{{ route('coupons.create') }}"><button class="btn btn-flat btn-success">New</button></a>
                            @if(session()->has('message_alert'))
                                <br>
                                <br>
                                <p class="alert alert-success">{{ session('message_alert') }}</p>
                            @endif
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="table-responsive">
                                <table id="example2" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Code</th>
                                        <th>Type</th>
                                        <th>Percent Off(%)</th>
                                        <th>Price Off($)</th>
                                        <th>Send</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($coupons as $coupon)
                                        <tr>
                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>{{ $coupon->code }}</td>
                                            <td>{{ $coupon->coupon_type }}</td>
                                            <td>@if($coupon->percent_off) {{ $coupon->percent_off }} @else - @endif</td>
                                            <td>@if($coupon->price_off) {{ $coupon->price_off }} @else - @endif</td>
                                            <td>
                                                <form action="{{ route('coupons.send') }}" method="POST">
                                                    @csrf
                                                    <input type="hidden" name="code" value="{{ $coupon->code }}">
                                                    <button type="submit" class="btn btn-flat btn-block btn-info"><span class="fa fa-send"></span></button>
                                                </form>
                                            </td>
                                            <td>
                                                <a href="{{ route('coupons.edit',$coupon->id) }}">
                                                    <button class="btn btn-flat btn-block btn-warning"><span class="fa fa-edit"></span></button>
                                                </a>
                                            </td>
                                            <td>
                                                <form id="delete-form-{{ $coupon->id }}" method="POST" action="{{ route('coupons.destroy',$coupon->id) }}" style="display: none;">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                                <a href="" onclick="if(confirm('Do you really want to delete this coupon?')){
                                                        event.preventDefault();
                                                        document.getElementById('delete-form-{{ $coupon->id }}').submit();
                                                        }else{
                                                        event.preventDefault();
                                                        }">
                                                    <button class="btn btn-flat btn-block btn-danger"><span class="fa fa-trash"></span></button>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Code</th>
                                        <th>Type</th>
                                        <th>Percent Off(%)</th>
                                        <th>Price Off($)</th>
                                        <th>Send</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

@endsection